-- Reset and reload lookup tables with clean data
-- This migration cleans all lookup tables and reloads them with proper data

-- Step 1: Clean up existing data (respecting foreign key constraints)
DELETE FROM countries;
DELETE FROM timezones;
DELETE FROM regions;

-- Step 2: Load regions data
INSERT INTO regions (display_name, name, is_parent, is_active) VALUES
('North America', 'north-america', false, true),
('South America', 'south-america', false, true),
('Central America', 'central-america', false, true),
('West Europe', 'west-europe', false, true),
('East Europe', 'east-europe', false, true),
('Africa', 'africa', true, true),
('Middle East', 'middle-east', false, false),
('Oceania', 'oceania', true, true),
('Americas', 'americas', true, true),
('Asia', 'asia', true, true),
('Europe', 'europe', true, true);

-- Step 3: Load timezones data (all 427 timezones)
INSERT INTO timezones (name, display_name, is_active) VALUES
('Africa/Abidjan', 'Africa/Abidjan (GMT)', true),
('Africa/Accra', 'Africa/Accra (GMT)', true),
('Africa/Addis_Ababa', 'Africa/Addis_Ababa (GMT)', true),
('Africa/Algiers', 'Africa/Algiers (GMT+1)', true),
('Africa/Asmara', 'Africa/Asmara (GMT)', true),
('Africa/Bamako', 'Africa/Bamako (GMT)', true),
('Africa/Bangui', 'Africa/Bangui (GMT)', true),
('Africa/Banjul', 'Africa/Banjul (GMT)', true),
('Africa/Bissau', 'Africa/Bissau (GMT)', true),
('Africa/Blantyre', 'Africa/Blantyre (GMT)', true),
('Africa/Brazzaville', 'Africa/Brazzaville (GMT)', true),
('Africa/Bujumbura', 'Africa/Bujumbura (GMT)', true),
('Africa/Cairo', 'Africa/Cairo (GMT+2)', true),
('Africa/Casablanca', 'Africa/Casablanca (GMT)', true),
('Africa/Ceuta', 'Africa/Ceuta (GMT+1)', true),
('Africa/Conakry', 'Africa/Conakry (GMT)', true),
('Africa/Dakar', 'Africa/Dakar (GMT)', true),
('Africa/Dar_es_Salaam', 'Africa/Dar_es_Salaam (GMT+3)', true),
('Africa/Djibouti', 'Africa/Djibouti (GMT+3)', true),
('Africa/Douala', 'Africa/Douala (GMT)', true),
('Africa/El_Aaiun', 'Africa/El_Aaiun (GMT)', true),
('Africa/Freetown', 'Africa/Freetown (GMT)', true),
('Africa/Gaborone', 'Africa/Gaborone (GMT)', true),
('Africa/Harare', 'Africa/Harare (GMT)', true),
('Africa/Johannesburg', 'Africa/Johannesburg (GMT+2)', true),
('Africa/Juba', 'Africa/Juba (GMT)', true),
('Africa/Kampala', 'Africa/Kampala (GMT)', true),
('Africa/Khartoum', 'Africa/Khartoum (GMT+2)', true),
('Africa/Kigali', 'Africa/Kigali (GMT)', true),
('Africa/Kinshasa', 'Africa/Kinshasa (GMT)', true),
('Africa/Lagos', 'Africa/Lagos (GMT+1)', true),
('Africa/Libreville', 'Africa/Libreville (GMT)', true),
('Africa/Lome', 'Africa/Lome (GMT)', true),
('Africa/Luanda', 'Africa/Luanda (GMT)', true),
('Africa/Lubumbashi', 'Africa/Lubumbashi (GMT+2)', true),
('Africa/Lusaka', 'Africa/Lusaka (GMT)', true),
('Africa/Malabo', 'Africa/Malabo (GMT)', true),
('Africa/Maputo', 'Africa/Maputo (GMT+2)', true),
('Africa/Maseru', 'Africa/Maseru (GMT)', true),
('Africa/Mbabane', 'Africa/Mbabane (GMT)', true),
('Africa/Mogadishu', 'Africa/Mogadishu (GMT)', true),
('Africa/Monrovia', 'Africa/Monrovia (GMT)', true),
('Africa/Nairobi', 'Africa/Nairobi (GMT+3)', true),
('Africa/Ndjamena', 'Africa/Ndjamena (GMT+1)', true),
('Africa/Niamey', 'Africa/Niamey (GMT)', true),
('Africa/Nouakchott', 'Africa/Nouakchott (GMT)', true),
('Africa/Ouagadougou', 'Africa/Ouagadougou (GMT)', true),
('Africa/Porto-Novo', 'Africa/Porto-Novo (GMT)', true),
('Africa/Sao_Tome', 'Africa/Sao_Tome (GMT)', true),
('Africa/Tripoli', 'Africa/Tripoli (GMT+2)', true),
('Africa/Tunis', 'Africa/Tunis (GMT+1)', true),
('Africa/Windhoek', 'Africa/Windhoek (GMT+1)', true),
('America/Adak', 'America/Adak (GMT-10)', true),
('America/Anchorage', 'America/Anchorage (GMT-9)', true),
('America/Anguilla', 'America/Anguilla (GMT-4)', true),
('America/Antigua', 'America/Antigua (GMT)', true),
('America/Araguaina', 'America/Araguaina (GMT-3)', true),
('America/Argentina/Buenos_Aires', 'America/Argentina/Buenos_Aires (GMT-3)', true),
('America/Argentina/Catamarca', 'America/Argentina/Catamarca (GMT-3)', true),
('America/Argentina/Cordoba', 'America/Argentina/Cordoba (GMT-3)', true),
('America/Argentina/Jujuy', 'America/Argentina/Jujuy (GMT-3)', true),
('America/Argentina/La_Rioja', 'America/Argentina/La_Rioja (GMT-3)', true),
('America/Argentina/Mendoza', 'America/Argentina/Mendoza (GMT-3)', true),
('America/Argentina/Rio_Gallegos', 'America/Argentina/Rio_Gallegos (GMT-3)', true),
('America/Argentina/Salta', 'America/Argentina/Salta (GMT-3)', true),
('America/Argentina/San_Juan', 'America/Argentina/San_Juan (GMT-3)', true),
('America/Argentina/San_Luis', 'America/Argentina/San_Luis (GMT-3)', true),
('America/Argentina/Tucuman', 'America/Argentina/Tucuman (GMT-3)', true),
('America/Argentina/Ushuaia', 'America/Argentina/Ushuaia (GMT-3)', true),
('America/Aruba', 'America/Aruba (GMT-4)', true),
('America/Asuncion', 'America/Asuncion (GMT-4)', true),
('America/Atikokan', 'America/Atikokan (GMT-5)', true),
('America/Bahia', 'America/Bahia (GMT-3)', true),
('America/Bahia_Banderas', 'America/Bahia_Banderas (GMT-6)', true),
('America/Barbados', 'America/Barbados (GMT-4)', true),
('America/Belem', 'America/Belem (GMT-3)', true),
('America/Belize', 'America/Belize (GMT-6)', true),
('America/Blanc-Sablon', 'America/Blanc-Sablon (GMT-4)', true),
('America/Boa_Vista', 'America/Boa_Vista (GMT-4)', true),
('America/Bogota', 'America/Bogota (GMT-5)', true),
('America/Boise', 'America/Boise (GMT-7)', true),
('America/Cambridge_Bay', 'America/Cambridge_Bay (GMT-7)', true),
('America/Campo_Grande', 'America/Campo_Grande (GMT-4)', true),
('America/Cancun', 'America/Cancun (GMT-5)', true),
('America/Caracas', 'America/Caracas (GMT-4)', true),
('America/Cayenne', 'America/Cayenne (GMT-3)', true),
('America/Cayman', 'America/Cayman (GMT-5)', true),
('America/Chicago', 'America/Chicago (GMT-6)', true),
('America/Chihuahua', 'America/Chihuahua (GMT-7)', true),
('America/Costa_Rica', 'America/Costa_Rica (GMT-6)', true),
('America/Creston', 'America/Creston (GMT-7)', true),
('America/Cuiaba', 'America/Cuiaba (GMT-4)', true),
('America/Curacao', 'America/Curacao (GMT-4)', true),
('America/Danmarkshavn', 'America/Danmarkshavn (GMT)', true),
('America/Dawson', 'America/Dawson (GMT-8)', true),
('America/Dawson_Creek', 'America/Dawson_Creek (GMT-7)', true),
('America/Denver', 'America/Denver (GMT-7)', true),
('America/Detroit', 'America/Detroit (GMT-5)', true),
('America/Dominica', 'America/Dominica (GMT)', true),
('America/Edmonton', 'America/Edmonton (GMT-7)', true),
('America/Eirunepe', 'America/Eirunepe (GMT-5)', true),
('America/El_Salvador', 'America/El_Salvador (GMT-6)', true),
('America/Fort_Nelson', 'America/Fort_Nelson (GMT-7)', true),
('America/Fortaleza', 'America/Fortaleza (GMT-3)', true),
('America/Glace_Bay', 'America/Glace_Bay (GMT-4)', true),
('America/Godthab', 'America/Godthab (GMT-3)', true),
('America/Goose_Bay', 'America/Goose_Bay (GMT-4)', true),
('America/Grand_Turk', 'America/Grand_Turk (GMT-5)', true),
('America/Grenada', 'America/Grenada (GMT)', true),
('America/Guadeloupe', 'America/Guadeloupe (GMT-4)', true),
('America/Guatemala', 'America/Guatemala (GMT-6)', true),
('America/Guayaquil', 'America/Guayaquil (GMT-5)', true),
('America/Guyana', 'America/Guyana (GMT-4)', true),
('America/Halifax', 'America/Halifax (GMT-4)', true),
('America/Havana', 'America/Havana (GMT-5)', true),
('America/Hermosillo', 'America/Hermosillo (GMT-7)', true),
('America/Indiana/Indianapolis', 'America/Indiana/Indianapolis (GMT-5)', true),
('America/Indiana/Knox', 'America/Indiana/Knox (GMT-6)', true),
('America/Indiana/Marengo', 'America/Indiana/Marengo (GMT-5)', true),
('America/Indiana/Petersburg', 'America/Indiana/Petersburg (GMT-5)', true),
('America/Indiana/Tell_City', 'America/Indiana/Tell_City (GMT-6)', true),
('America/Indiana/Vevay', 'America/Indiana/Vevay (GMT-5)', true),
('America/Indiana/Vincennes', 'America/Indiana/Vincennes (GMT-5)', true),
('America/Indiana/Winamac', 'America/Indiana/Winamac (GMT-5)', true),
('America/Inuvik', 'America/Inuvik (GMT-7)', true),
('America/Iqaluit', 'America/Iqaluit (GMT-5)', true),
('America/Jamaica', 'America/Jamaica (GMT-5)', true),
('America/Juneau', 'America/Juneau (GMT-9)', true),
('America/Kentucky/Louisville', 'America/Kentucky/Louisville (GMT-5)', true),
('America/Kentucky/Monticello', 'America/Kentucky/Monticello (GMT-5)', true),
('America/Kralendijk', 'America/Kralendijk (GMT-4)', true),
('America/La_Paz', 'America/La_Paz (GMT-4)', true),
('America/Lima', 'America/Lima (GMT-5)', true),
('America/Los_Angeles', 'America/Los_Angeles (GMT-8)', true),
('America/Lower_Princes', 'America/Lower_Princes (GMT-4)', true),
('America/Maceio', 'America/Maceio (GMT-3)', true),
('America/Managua', 'America/Managua (GMT-6)', true),
('America/Manaus', 'America/Manaus (GMT-4)', true),
('America/Marigot', 'America/Marigot (GMT-4)', true),
('America/Martinique', 'America/Martinique (GMT-4)', true),
('America/Matamoros', 'America/Matamoros (GMT-6)', true),
('America/Mazatlan', 'America/Mazatlan (GMT-7)', true),
('America/Menominee', 'America/Menominee (GMT-6)', true),
('America/Merida', 'America/Merida (GMT-6)', true),
('America/Metlakatla', 'America/Metlakatla (GMT-9)', true),
('America/Mexico_City', 'America/Mexico_City (GMT-6)', true),
('America/Miquelon', 'America/Miquelon (GMT-3)', true),
('America/Moncton', 'America/Moncton (GMT-4)', true),
('America/Monterrey', 'America/Monterrey (GMT-6)', true),
('America/Montevideo', 'America/Montevideo (GMT-3)', true),
('America/Montserrat', 'America/Montserrat (GMT-4)', true),
('America/Nassau', 'America/Nassau (GMT-5)', true),
('America/New_York', 'America/New_York (GMT-5)', true),
('America/Nipigon', 'America/Nipigon (GMT-5)', true),
('America/Nome', 'America/Nome (GMT-9)', true),
('America/Noronha', 'America/Noronha (GMT-2)', true),
('America/North_Dakota/Beulah', 'America/North_Dakota/Beulah (GMT-6)', true),
('America/North_Dakota/Center', 'America/North_Dakota/Center (GMT-6)', true),
('America/North_Dakota/New_Salem', 'America/North_Dakota/New_Salem (GMT-6)', true),
('America/Ojinaga', 'America/Ojinaga (GMT-7)', true),
('America/Panama', 'America/Panama (GMT-5)', true),
('America/Pangnirtung', 'America/Pangnirtung (GMT-5)', true),
('America/Paramaribo', 'America/Paramaribo (GMT-3)', true),
('America/Phoenix', 'America/Phoenix (GMT-7)', true),
('America/Port-au-Prince', 'America/Port-au-Prince (GMT-5)', true),
('America/Port_of_Spain', 'America/Port_of_Spain (GMT-4)', true),
('America/Porto_Velho', 'America/Porto_Velho (GMT-4)', true),
('America/Puerto_Rico', 'America/Puerto_Rico (GMT-4)', true),
('America/Punta_Arenas', 'America/Punta_Arenas (GMT-3)', true),
('America/Rainy_River', 'America/Rainy_River (GMT-6)', true),
('America/Rankin_Inlet', 'America/Rankin_Inlet (GMT-6)', true),
('America/Recife', 'America/Recife (GMT-3)', true),
('America/Regina', 'America/Regina (GMT-6)', true),
('America/Resolute', 'America/Resolute (GMT-6)', true),
('America/Rio_Branco', 'America/Rio_Branco (GMT-5)', true),
('America/Santarem', 'America/Santarem (GMT-3)', true),
('America/Santiago', 'America/Santiago (GMT-4)', true),
('America/Santo_Domingo', 'America/Santo_Domingo (GMT-4)', true),
('America/Sao_Paulo', 'America/Sao_Paulo (GMT-3)', true),
('America/Scoresbysund', 'America/Scoresbysund (GMT-1)', true),
('America/Sitka', 'America/Sitka (GMT-9)', true),
('America/St_Barthelemy', 'America/St_Barthelemy (GMT-4)', true),
('America/St_Johns', 'America/St_Johns (GMT-3:30)', true),
('America/St_Kitts', 'America/St_Kitts (GMT)', true),
('America/St_Lucia', 'America/St_Lucia (GMT)', true),
('America/St_Thomas', 'America/St_Thomas (GMT-4)', true),
('America/St_Vincent', 'America/St_Vincent (GMT)', true),
('America/Swift_Current', 'America/Swift_Current (GMT-6)', true),
('America/Tegucigalpa', 'America/Tegucigalpa (GMT-6)', true),
('America/Thule', 'America/Thule (GMT-4)', true),
('America/Thunder_Bay', 'America/Thunder_Bay (GMT-5)', true),
('America/Tijuana', 'America/Tijuana (GMT-8)', true),
('America/Toronto', 'America/Toronto (GMT-5)', true),
('America/Tortola', 'America/Tortola (GMT-4)', true),
('America/Vancouver', 'America/Vancouver (GMT-8)', true),
('America/Whitehorse', 'America/Whitehorse (GMT-8)', true),
('America/Winnipeg', 'America/Winnipeg (GMT-6)', true),
('America/Yakutat', 'America/Yakutat (GMT-9)', true),
('America/Yellowknife', 'America/Yellowknife (GMT-7)', true),
('Antarctica/Casey', 'Antarctica/Casey (GMT+11)', true),
('Antarctica/Davis', 'Antarctica/Davis (GMT+7)', true),
('Antarctica/DumontDUrville', 'Antarctica/DumontDUrville (GMT+10)', true),
('Antarctica/Macquarie', 'Antarctica/Macquarie (GMT+11)', true),
('Antarctica/Mawson', 'Antarctica/Mawson (GMT+5)', true),
('Antarctica/McMurdo', 'Antarctica/McMurdo (GMT+13)', true),
('Antarctica/Palmer', 'Antarctica/Palmer (GMT-3)', true),
('Antarctica/Rothera', 'Antarctica/Rothera (GMT-3)', true),
('Antarctica/Syowa', 'Antarctica/Syowa (GMT+3)', true),
('Antarctica/Troll', 'Antarctica/Troll (GMT)', true),
('Antarctica/Vostok', 'Antarctica/Vostok (GMT+6)', true),
('Arctic/Longyearbyen', 'Arctic/Longyearbyen (GMT+1)', true),
('Asia/Aden', 'Asia/Aden (GMT)', true),
('Asia/Almaty', 'Asia/Almaty (GMT+6)', true),
('Asia/Amman', 'Asia/Amman (GMT+2)', true),
('Asia/Anadyr', 'Asia/Anadyr (GMT+12)', true),
('Asia/Aqtau', 'Asia/Aqtau (GMT+5)', true),
('Asia/Aqtobe', 'Asia/Aqtobe (GMT+5)', true),
('Asia/Ashgabat', 'Asia/Ashgabat (GMT+5)', true),
('Asia/Atyrau', 'Asia/Atyrau (GMT+5)', true),
('Asia/Baghdad', 'Asia/Baghdad (GMT+3)', true),
('Asia/Bahrain', 'Asia/Bahrain (GMT)', true),
('Asia/Baku', 'Asia/Baku (GMT+4)', true),
('Asia/Bangkok', 'Asia/Bangkok (GMT+7)', true),
('Asia/Barnaul', 'Asia/Barnaul (GMT+7)', true),
('Asia/Beirut', 'Asia/Beirut (GMT+2)', true),
('Asia/Bishkek', 'Asia/Bishkek (GMT+6)', true),
('Asia/Brunei', 'Asia/Brunei (GMT+8)', true),
('Asia/Chita', 'Asia/Chita (GMT+9)', true),
('Asia/Choibalsan', 'Asia/Choibalsan (GMT+8)', true),
('Asia/Colombo', 'Asia/Colombo (GMT+5:30)', true),
('Asia/Damascus', 'Asia/Damascus (GMT+2)', true),
('Asia/Dhaka', 'Asia/Dhaka (GMT+6)', true),
('Asia/Dili', 'Asia/Dili (GMT+9)', true),
('Asia/Dubai', 'Asia/Dubai (GMT+4)', true),
('Asia/Dushanbe', 'Asia/Dushanbe (GMT+5)', true),
('Asia/Famagusta', 'Asia/Famagusta (GMT+2)', true),
('Asia/Gaza', 'Asia/Gaza (GMT+2)', true),
('Asia/Hebron', 'Asia/Hebron (GMT+2)', true),
('Asia/Ho_Chi_Minh', 'Asia/Ho_Chi_Minh (GMT+7)', true),
('Asia/Hong_Kong', 'Asia/Hong_Kong (GMT+8)', true),
('Asia/Hovd', 'Asia/Hovd (GMT+7)', true),
('Asia/Irkutsk', 'Asia/Irkutsk (GMT+8)', true),
('Asia/Jakarta', 'Asia/Jakarta (GMT+7)', true),
('Asia/Jayapura', 'Asia/Jayapura (GMT+9)', true),
('Asia/Jerusalem', 'Asia/Jerusalem (GMT+2)', true),
('Asia/Kabul', 'Asia/Kabul (GMT+4:30)', true),
('Asia/Kamchatka', 'Asia/Kamchatka (GMT+12)', true),
('Asia/Karachi', 'Asia/Karachi (GMT+5)', true),
('Asia/Kathmandu', 'Asia/Kathmandu (GMT+5:45)', true),
('Asia/Khandyga', 'Asia/Khandyga (GMT+9)', true),
('Asia/Kolkata', 'Asia/Kolkata (GMT+5:30)', true),
('Asia/Krasnoyarsk', 'Asia/Krasnoyarsk (GMT+7)', true),
('Asia/Kuala_Lumpur', 'Asia/Kuala_Lumpur (GMT+8)', true),
('Asia/Kuching', 'Asia/Kuching (GMT+8)', true),
('Asia/Kuwait', 'Asia/Kuwait (GMT)', true),
('Asia/Macau', 'Asia/Macau (GMT+8)', true),
('Asia/Magadan', 'Asia/Magadan (GMT+11)', true),
('Asia/Makassar', 'Asia/Makassar (GMT+8)', true),
('Asia/Manila', 'Asia/Manila (GMT+8)', true),
('Asia/Muscat', 'Asia/Muscat (GMT)', true),
('Asia/Nicosia', 'Asia/Nicosia (GMT+2)', true),
('Asia/Novokuznetsk', 'Asia/Novokuznetsk (GMT+7)', true),
('Asia/Novosibirsk', 'Asia/Novosibirsk (GMT+7)', true),
('Asia/Omsk', 'Asia/Omsk (GMT+6)', true),
('Asia/Oral', 'Asia/Oral (GMT+5)', true),
('Asia/Phnom_Penh', 'Asia/Phnom_Penh (GMT+7)', true),
('Asia/Pontianak', 'Asia/Pontianak (GMT+7)', true),
('Asia/Pyongyang', 'Asia/Pyongyang (GMT+9)', true),
('Asia/Qatar', 'Asia/Qatar (GMT+3)', true),
('Asia/Qostanay', 'Asia/Qostanay (GMT+6)', true),
('Asia/Qyzylorda', 'Asia/Qyzylorda (GMT+5)', true),
('Asia/Rangoon', 'Asia/Rangoon (GMT+6:30)', true),
('Asia/Riyadh', 'Asia/Riyadh (GMT+3)', true),
('Asia/Sakhalin', 'Asia/Sakhalin (GMT+11)', true),
('Asia/Samarkand', 'Asia/Samarkand (GMT+5)', true),
('Asia/Seoul', 'Asia/Seoul (GMT+9)', true),
('Asia/Shanghai', 'Asia/Shanghai (GMT+8)', true),
('Asia/Singapore', 'Asia/Singapore (GMT+8)', true),
('Asia/Srednekolymsk', 'Asia/Srednekolymsk (GMT+11)', true),
('Asia/Taipei', 'Asia/Taipei (GMT+8)', true),
('Asia/Tashkent', 'Asia/Tashkent (GMT+5)', true),
('Asia/Tbilisi', 'Asia/Tbilisi (GMT+4)', true),
('Asia/Tehran', 'Asia/Tehran (GMT+3:30)', true),
('Asia/Thimphu', 'Asia/Thimphu (GMT+6)', true),
('Asia/Tokyo', 'Asia/Tokyo (GMT+9)', true),
('Asia/Tomsk', 'Asia/Tomsk (GMT+7)', true),
('Asia/Ulaanbaatar', 'Asia/Ulaanbaatar (GMT+8)', true),
('Asia/Urumqi', 'Asia/Urumqi (GMT+6)', true),
('Asia/Ust-Nera', 'Asia/Ust-Nera (GMT+10)', true),
('Asia/Vientiane', 'Asia/Vientiane (GMT+7)', true),
('Asia/Vladivostok', 'Asia/Vladivostok (GMT+10)', true),
('Asia/Yakutsk', 'Asia/Yakutsk (GMT+9)', true),
('Asia/Yangon', 'Asia/Yangon (GMT+6:30)', true),
('Asia/Yekaterinburg', 'Asia/Yekaterinburg (GMT+5)', true),
('Asia/Yerevan', 'Asia/Yerevan (GMT+4)', true),
('Atlantic/Azores', 'Atlantic/Azores (GMT-1)', true),
('Atlantic/Bermuda', 'Atlantic/Bermuda (GMT-4)', true),
('Atlantic/Canary', 'Atlantic/Canary (GMT)', true),
('Atlantic/Cape_Verde', 'Atlantic/Cape_Verde (GMT-1)', true),
('Atlantic/Faroe', 'Atlantic/Faroe (GMT)', true),
('Atlantic/Madeira', 'Atlantic/Madeira (GMT)', true),
('Atlantic/Reykjavik', 'Atlantic/Reykjavik (GMT)', true),
('Atlantic/South_Georgia', 'Atlantic/South_Georgia (GMT-2)', true),
('Atlantic/St_Helena', 'Atlantic/St_Helena (GMT)', true),
('Atlantic/Stanley', 'Atlantic/Stanley (GMT-3)', true),
('Australia/Adelaide', 'Australia/Adelaide (GMT+9:30)', true),
('Australia/Brisbane', 'Australia/Brisbane (GMT+10)', true),
('Australia/Broken_Hill', 'Australia/Broken_Hill (GMT+9:30)', true),
('Australia/Currie', 'Australia/Currie (GMT+10)', true),
('Australia/Darwin', 'Australia/Darwin (GMT+9:30)', true),
('Australia/Eucla', 'Australia/Eucla (GMT+8:45)', true),
('Australia/Hobart', 'Australia/Hobart (GMT+10)', true),
('Australia/Lindeman', 'Australia/Lindeman (GMT+10)', true),
('Australia/Lord_Howe', 'Australia/Lord_Howe (GMT+10:30)', true),
('Australia/Melbourne', 'Australia/Melbourne (GMT+10)', true),
('Australia/Perth', 'Australia/Perth (GMT+8)', true),
('Australia/Sydney', 'Australia/Sydney (GMT+10)', true),
('Europe/Amsterdam', 'Europe/Amsterdam (GMT+1)', true),
('Europe/Andorra', 'Europe/Andorra (GMT+1)', true),
('Europe/Astrakhan', 'Europe/Astrakhan (GMT+4)', true),
('Europe/Athens', 'Europe/Athens (GMT+2)', true),
('Europe/Belgrade', 'Europe/Belgrade (GMT+1)', true),
('Europe/Berlin', 'Europe/Berlin (GMT+1)', true),
('Europe/Bratislava', 'Europe/Bratislava (GMT)', true),
('Europe/Brussels', 'Europe/Brussels (GMT+1)', true),
('Europe/Bucharest', 'Europe/Bucharest (GMT+2)', true),
('Europe/Budapest', 'Europe/Budapest (GMT+1)', true),
('Europe/Busingen', 'Europe/Busingen (GMT+1)', true),
('Europe/Chisinau', 'Europe/Chisinau (GMT+2)', true),
('Europe/Copenhagen', 'Europe/Copenhagen (GMT+1)', true),
('Europe/Dublin', 'Europe/Dublin (GMT)', true),
('Europe/Gibraltar', 'Europe/Gibraltar (GMT+1)', true),
('Europe/Guernsey', 'Europe/Guernsey (GMT)', true),
('Europe/Helsinki', 'Europe/Helsinki (GMT+2)', true),
('Europe/Isle_of_Man', 'Europe/Isle_of_Man (GMT)', true),
('Europe/Istanbul', 'Europe/Istanbul (GMT+3)', true),
('Europe/Jersey', 'Europe/Jersey (GMT)', true),
('Europe/Kaliningrad', 'Europe/Kaliningrad (GMT+2)', true),
('Europe/Kiev', 'Europe/Kiev (GMT+2)', true),
('Europe/Kirov', 'Europe/Kirov (GMT+3)', true),
('Europe/Lisbon', 'Europe/Lisbon (GMT)', true),
('Europe/Ljubljana', 'Europe/Ljubljana (GMT)', true),
('Europe/London', 'Europe/London (GMT)', true),
('Europe/Luxembourg', 'Europe/Luxembourg (GMT+1)', true),
('Europe/Madrid', 'Europe/Madrid (GMT+1)', true),
('Europe/Malta', 'Europe/Malta (GMT+1)', true),
('Europe/Mariehamn', 'Europe/Mariehamn (GMT+2)', true),
('Europe/Minsk', 'Europe/Minsk (GMT+3)', true),
('Europe/Monaco', 'Europe/Monaco (GMT+1)', true),
('Europe/Moscow', 'Europe/Moscow (GMT+3)', true),
('Europe/Oslo', 'Europe/Oslo (GMT+1)', true),
('Europe/Paris', 'Europe/Paris (GMT+1)', true),
('Europe/Podgorica', 'Europe/Podgorica (GMT)', true),
('Europe/Prague', 'Europe/Prague (GMT+1)', true),
('Europe/Riga', 'Europe/Riga (GMT+2)', true),
('Europe/Rome', 'Europe/Rome (GMT+1)', true),
('Europe/Samara', 'Europe/Samara (GMT+4)', true),
('Europe/San_Marino', 'Europe/San_Marino (GMT)', true),
('Europe/Sarajevo', 'Europe/Sarajevo (GMT)', true),
('Europe/Saratov', 'Europe/Saratov (GMT+4)', true),
('Europe/Simferopol', 'Europe/Simferopol (GMT+3)', true),
('Europe/Skopje', 'Europe/Skopje (GMT)', true),
('Europe/Sofia', 'Europe/Sofia (GMT+2)', true),
('Europe/Stockholm', 'Europe/Stockholm (GMT+1)', true),
('Europe/Tallinn', 'Europe/Tallinn (GMT+2)', true),
('Europe/Tirane', 'Europe/Tirane (GMT+1)', true),
('Europe/Ulyanovsk', 'Europe/Ulyanovsk (GMT+4)', true),
('Europe/Uzhgorod', 'Europe/Uzhgorod (GMT+2)', true),
('Europe/Vaduz', 'Europe/Vaduz (GMT)', true),
('Europe/Vatican', 'Europe/Vatican (GMT)', true),
('Europe/Vienna', 'Europe/Vienna (GMT+1)', true),
('Europe/Vilnius', 'Europe/Vilnius (GMT+2)', true),
('Europe/Volgograd', 'Europe/Volgograd (GMT+4)', true),
('Europe/Warsaw', 'Europe/Warsaw (GMT+1)', true),
('Europe/Zagreb', 'Europe/Zagreb (GMT)', true),
('Europe/Zaporozhye', 'Europe/Zaporozhye (GMT+2)', true),
('Europe/Zurich', 'Europe/Zurich (GMT+1)', true),
('Indian/Antananarivo', 'Indian/Antananarivo (GMT)', true),
('Indian/Chagos', 'Indian/Chagos (GMT+6)', true),
('Indian/Christmas', 'Indian/Christmas (GMT+7)', true),
('Indian/Cocos', 'Indian/Cocos (GMT+6:30)', true),
('Indian/Comoro', 'Indian/Comoro (GMT)', true),
('Indian/Kerguelen', 'Indian/Kerguelen (GMT+5)', true),
('Indian/Mahe', 'Indian/Mahe (GMT+4)', true),
('Indian/Maldives', 'Indian/Maldives (GMT+5)', true),
('Indian/Mauritius', 'Indian/Mauritius (GMT+4)', true),
('Indian/Mayotte', 'Indian/Mayotte (GMT+3)', true),
('Indian/Reunion', 'Indian/Reunion (GMT+4)', true),
('Pacific/Apia', 'Pacific/Apia (GMT+13)', true),
('Pacific/Auckland', 'Pacific/Auckland (GMT+13)', true),
('Pacific/Bougainville', 'Pacific/Bougainville (GMT+11)', true),
('Pacific/Chatham', 'Pacific/Chatham (GMT+12:45)', true),
('Pacific/Chuuk', 'Pacific/Chuuk (GMT+10)', true),
('Pacific/Easter', 'Pacific/Easter (GMT-5)', true),
('Pacific/Efate', 'Pacific/Efate (GMT+11)', true),
('Pacific/Enderbury', 'Pacific/Enderbury (GMT+13)', true),
('Pacific/Fakaofo', 'Pacific/Fakaofo (GMT+13)', true),
('Pacific/Fiji', 'Pacific/Fiji (GMT+12)', true),
('Pacific/Funafuti', 'Pacific/Funafuti (GMT+12)', true),
('Pacific/Galapagos', 'Pacific/Galapagos (GMT-6)', true),
('Pacific/Gambier', 'Pacific/Gambier (GMT-9)', true),
('Pacific/Guadalcanal', 'Pacific/Guadalcanal (GMT+11)', true),
('Pacific/Guam', 'Pacific/Guam (GMT+10)', true),
('Pacific/Honolulu', 'Pacific/Honolulu (GMT-10)', true),
('Pacific/Kiritimati', 'Pacific/Kiritimati (GMT+14)', true),
('Pacific/Kosrae', 'Pacific/Kosrae (GMT+11)', true),
('Pacific/Kwajalein', 'Pacific/Kwajalein (GMT+12)', true),
('Pacific/Majuro', 'Pacific/Majuro (GMT+12)', true),
('Pacific/Marquesas', 'Pacific/Marquesas (GMT-9:30)', true),
('Pacific/Midway', 'Pacific/Midway (GMT-11)', true),
('Pacific/Nauru', 'Pacific/Nauru (GMT+12)', true),
('Pacific/Niue', 'Pacific/Niue (GMT-11)', true),
('Pacific/Norfolk', 'Pacific/Norfolk (GMT+11)', true),
('Pacific/Noumea', 'Pacific/Noumea (GMT+11)', true),
('Pacific/Pago_Pago', 'Pacific/Pago_Pago (GMT-11)', true),
('Pacific/Palau', 'Pacific/Palau (GMT+9)', true),
('Pacific/Pitcairn', 'Pacific/Pitcairn (GMT-8)', true),
('Pacific/Pohnpei', 'Pacific/Pohnpei (GMT+11)', true),
('Pacific/Port_Moresby', 'Pacific/Port_Moresby (GMT+10)', true),
('Pacific/Rarotonga', 'Pacific/Rarotonga (GMT-10)', true),
('Pacific/Saipan', 'Pacific/Saipan (GMT+10)', true),
('Pacific/Tahiti', 'Pacific/Tahiti (GMT-10)', true),
('Pacific/Tarawa', 'Pacific/Tarawa (GMT+12)', true),
('Pacific/Tongatapu', 'Pacific/Tongatapu (GMT+13)', true),
('Pacific/Wake', 'Pacific/Wake (GMT+12)', true),
('Pacific/Wallis', 'Pacific/Wallis (GMT+12)', true);

-- Step 4: Load countries data (all 248 countries)
INSERT INTO countries (iso_code, display_name, region, region_parent, primary_timezone, is_active) VALUES
('US', 'United States', 'north-america', 'americas', 'America/New_York', true),
('CA', 'Canada', 'north-america', 'americas', 'America/Toronto', true),
('MX', 'Mexico', 'north-america', 'americas', 'America/Mexico_City', true),
('BZ', 'Belize', 'central-america', 'americas', 'America/Belize', true),
('CR', 'Costa Rica', 'central-america', 'americas', 'America/Costa_Rica', true),
('SV', 'El Salvador', 'central-america', 'americas', 'America/El_Salvador', true),
('GT', 'Guatemala', 'central-america', 'americas', 'America/Guatemala', true),
('HN', 'Honduras', 'central-america', 'americas', 'America/Tegucigalpa', true),
('NI', 'Nicaragua', 'central-america', 'americas', 'America/Managua', true),
('PA', 'Panama', 'central-america', 'americas', 'America/Panama', true),
('AG', 'Antigua and Barbuda', 'central-america', 'americas', 'America/Antigua', true),
('BS', 'Bahamas', 'north-america', 'americas', 'America/Nassau', true),
('BB', 'Barbados', 'north-america', 'americas', 'America/Barbados', true),
('CU', 'Cuba', 'north-america', 'americas', 'America/Havana', true),
('DM', 'Dominica', 'north-america', 'americas', 'America/Dominica', true),
('DO', 'Dominican Republic', 'north-america', 'americas', 'America/Santo_Domingo', true),
('GD', 'Grenada', 'north-america', 'americas', 'America/Grenada', true),
('HT', 'Haiti', 'north-america', 'americas', 'America/Port-au-Prince', true),
('JM', 'Jamaica', 'north-america', 'americas', 'America/Jamaica', true),
('KN', 'Saint Kitts and Nevis', 'north-america', 'americas', 'America/St_Kitts', true),
('LC', 'Saint Lucia', 'north-america', 'americas', 'America/St_Lucia', true),
('VC', 'Saint Vincent and the Grenadines', 'north-america', 'americas', 'America/St_Vincent', true),
('TT', 'Trinidad and Tobago', 'north-america', 'americas', 'America/Port_of_Spain', true),
('AR', 'Argentina', 'south-america', 'americas', 'America/Argentina/Buenos_Aires', true),
('BO', 'Bolivia', 'south-america', 'americas', 'America/La_Paz', true),
('BR', 'Brazil', 'south-america', 'americas', 'America/Sao_Paulo', true),
('CL', 'Chile', 'south-america', 'americas', 'America/Santiago', true),
('CO', 'Colombia', 'south-america', 'americas', 'America/Bogota', true),
('EC', 'Ecuador', 'south-america', 'americas', 'America/Guayaquil', true),
('GY', 'Guyana', 'south-america', 'americas', 'America/Guyana', true),
('PY', 'Paraguay', 'south-america', 'americas', 'America/Asuncion', true),
('PE', 'Peru', 'south-america', 'americas', 'America/Lima', true),
('SR', 'Suriname', 'south-america', 'americas', 'America/Paramaribo', true),
('UY', 'Uruguay', 'south-america', 'americas', 'America/Montevideo', true),
('VE', 'Venezuela', 'south-america', 'americas', 'America/Caracas', true),
('AD', 'Andorra', 'west-europe', 'europe', 'Europe/Andorra', true),
('AT', 'Austria', 'west-europe', 'europe', 'Europe/Vienna', true),
('BE', 'Belgium', 'west-europe', 'europe', 'Europe/Brussels', true),
('DK', 'Denmark', 'west-europe', 'europe', 'Europe/Copenhagen', true),
('FI', 'Finland', 'west-europe', 'europe', 'Europe/Helsinki', true),
('FR', 'France', 'west-europe', 'europe', 'Europe/Paris', true),
('DE', 'Germany', 'west-europe', 'europe', 'Europe/Berlin', true),
('GR', 'Greece', 'west-europe', 'europe', 'Europe/Athens', true),
('IS', 'Iceland', 'west-europe', 'europe', 'Atlantic/Reykjavik', true),
('IE', 'Ireland', 'west-europe', 'europe', 'Europe/Dublin', true),
('IT', 'Italy', 'west-europe', 'europe', 'Europe/Rome', true),
('LI', 'Liechtenstein', 'west-europe', 'europe', 'Europe/Vaduz', true),
('LU', 'Luxembourg', 'west-europe', 'europe', 'Europe/Luxembourg', true),
('MT', 'Malta', 'west-europe', 'europe', 'Europe/Malta', true),
('MC', 'Monaco', 'west-europe', 'europe', 'Europe/Monaco', true),
('NL', 'Netherlands', 'west-europe', 'europe', 'Europe/Amsterdam', true),
('NO', 'Norway', 'west-europe', 'europe', 'Europe/Oslo', true),
('PT', 'Portugal', 'west-europe', 'europe', 'Europe/Lisbon', true),
('SM', 'San Marino', 'west-europe', 'europe', 'Europe/San_Marino', true),
('ES', 'Spain', 'west-europe', 'europe', 'Europe/Madrid', true),
('SE', 'Sweden', 'west-europe', 'europe', 'Europe/Stockholm', true),
('CH', 'Switzerland', 'west-europe', 'europe', 'Europe/Zurich', true),
('GB', 'United Kingdom', 'west-europe', 'europe', 'Europe/London', true),
('VA', 'Vatican City', 'west-europe', 'europe', 'Europe/Vatican', true),
('AL', 'Albania', 'east-europe', 'europe', 'Europe/Tirane', true),
('BA', 'Bosnia and Herzegovina', 'east-europe', 'europe', 'Europe/Sarajevo', true),
('BG', 'Bulgaria', 'east-europe', 'europe', 'Europe/Sofia', true),
('HR', 'Croatia', 'east-europe', 'europe', 'Europe/Zagreb', true),
('CZ', 'Czech Republic', 'east-europe', 'europe', 'Europe/Prague', true),
('EE', 'Estonia', 'east-europe', 'europe', 'Europe/Tallinn', true),
('HU', 'Hungary', 'east-europe', 'europe', 'Europe/Budapest', true),
('LV', 'Latvia', 'east-europe', 'europe', 'Europe/Riga', true),
('LT', 'Lithuania', 'east-europe', 'europe', 'Europe/Vilnius', true),
('MK', 'North Macedonia', 'east-europe', 'europe', 'Europe/Skopje', true),
('MD', 'Moldova', 'east-europe', 'europe', 'Europe/Chisinau', true),
('ME', 'Montenegro', 'east-europe', 'europe', 'Europe/Podgorica', true),
('PL', 'Poland', 'east-europe', 'europe', 'Europe/Warsaw', true),
('RO', 'Romania', 'east-europe', 'europe', 'Europe/Bucharest', true),
('RS', 'Serbia', 'east-europe', 'europe', 'Europe/Belgrade', true),
('SK', 'Slovakia', 'east-europe', 'europe', 'Europe/Bratislava', true),
('SI', 'Slovenia', 'east-europe', 'europe', 'Europe/Ljubljana', true),
('UA', 'Ukraine', 'east-europe', 'europe', 'Europe/Kiev', true),
('BY', 'Belarus', 'east-europe', 'europe', 'Europe/Minsk', true),
('RU', 'Russia', 'east-europe', 'europe', 'Europe/Moscow', true),
('TR', 'Turkey', 'east-europe', 'europe', 'Europe/Istanbul', true),
('CN', 'China', NULL, 'asia', 'Asia/Shanghai', true),
('JP', 'Japan', NULL, 'asia', 'Asia/Tokyo', true),
('KR', 'South Korea', NULL, 'asia', 'Asia/Seoul', true),
('MY', 'Malaysia', NULL, 'asia', 'Asia/Kuala_Lumpur', true),
('SG', 'Singapore', NULL, 'asia', 'Asia/Singapore', true),
('TW', 'Taiwan', NULL, 'asia', 'Asia/Taipei', true),
('TH', 'Thailand', NULL, 'asia', 'Asia/Bangkok', true),
('VN', 'Vietnam', NULL, 'asia', 'Asia/Ho_Chi_Minh', true),
('PH', 'Philippines', NULL, 'asia', 'Asia/Manila', true),
('ID', 'Indonesia', NULL, 'asia', 'Asia/Jakarta', true),
('HK', 'Hong Kong', NULL, 'asia', 'Asia/Hong_Kong', true),
('AF', 'Afghanistan', NULL, 'asia', 'Asia/Kabul', true),
('BD', 'Bangladesh', NULL, 'asia', 'Asia/Dhaka', true),
('BT', 'Bhutan', NULL, 'asia', 'Asia/Thimphu', true),
('IN', 'India', NULL, 'asia', 'Asia/Kolkata', true),
('MV', 'Maldives', NULL, 'asia', 'Indian/Maldives', true),
('NP', 'Nepal', NULL, 'asia', 'Asia/Kathmandu', true),
('PK', 'Pakistan', NULL, 'asia', 'Asia/Karachi', true),
('LK', 'Sri Lanka', NULL, 'asia', 'Asia/Colombo', true),
('BH', 'Bahrain', NULL, 'asia', 'Asia/Bahrain', true),
('IR', 'Iran', NULL, 'asia', 'Asia/Tehran', true),
('IQ', 'Iraq', NULL, 'asia', 'Asia/Baghdad', true),
('IL', 'Israel', NULL, 'asia', 'Asia/Jerusalem', true),
('JO', 'Jordan', NULL, 'asia', 'Asia/Amman', true),
('KW', 'Kuwait', NULL, 'asia', 'Asia/Kuwait', true),
('LB', 'Lebanon', NULL, 'asia', 'Asia/Beirut', true),
('OM', 'Oman', NULL, 'asia', 'Asia/Muscat', true),
('QA', 'Qatar', NULL, 'asia', 'Asia/Qatar', true),
('SA', 'Saudi Arabia', NULL, 'asia', 'Asia/Riyadh', true),
('SY', 'Syria', NULL, 'asia', 'Asia/Damascus', true),
('AE', 'United Arab Emirates', NULL, 'asia', 'Asia/Dubai', true),
('YE', 'Yemen', NULL, 'asia', 'Asia/Aden', true),
('DZ', 'Algeria', NULL, 'africa', 'Africa/Algiers', true),
('AO', 'Angola', NULL, 'africa', 'Africa/Luanda', true),
('BJ', 'Benin', NULL, 'africa', 'Africa/Porto-Novo', true),
('BW', 'Botswana', NULL, 'africa', 'Africa/Gaborone', true),
('BF', 'Burkina Faso', NULL, 'africa', 'Africa/Ouagadougou', true),
('BI', 'Burundi', NULL, 'africa', 'Africa/Bujumbura', true),
('CM', 'Cameroon', NULL, 'africa', 'Africa/Douala', true),
('CV', 'Cape Verde', NULL, 'africa', 'Atlantic/Cape_Verde', true),
('CF', 'Central African Republic', NULL, 'africa', 'Africa/Bangui', true),
('TD', 'Chad', NULL, 'africa', 'Africa/Ndjamena', true),
('KM', 'Comoros', NULL, 'africa', 'Indian/Comoro', true),
('CG', 'Congo', NULL, 'africa', 'Africa/Brazzaville', true),
('CD', 'Democratic Republic of the Congo', NULL, 'africa', 'Africa/Kinshasa', true),
('DJ', 'Djibouti', NULL, 'africa', 'Africa/Djibouti', true),
('EG', 'Egypt', NULL, 'africa', 'Africa/Cairo', true),
('GQ', 'Equatorial Guinea', NULL, 'africa', 'Africa/Malabo', true),
('ER', 'Eritrea', NULL, 'africa', 'Africa/Asmara', true),
('ET', 'Ethiopia', NULL, 'africa', 'Africa/Addis_Ababa', true),
('GA', 'Gabon', NULL, 'africa', 'Africa/Libreville', true),
('GM', 'Gambia', NULL, 'africa', 'Africa/Banjul', true),
('GH', 'Ghana', NULL, 'africa', 'Africa/Accra', true),
('GN', 'Guinea', NULL, 'africa', 'Africa/Conakry', true),
('GW', 'Guinea-Bissau', NULL, 'africa', 'Africa/Bissau', true),
('CI', 'Ivory Coast', NULL, 'africa', 'Africa/Abidjan', true),
('KE', 'Kenya', NULL, 'africa', 'Africa/Nairobi', true),
('LS', 'Lesotho', NULL, 'africa', 'Africa/Maseru', true),
('LR', 'Liberia', NULL, 'africa', 'Africa/Monrovia', true),
('LY', 'Libya', NULL, 'africa', 'Africa/Tripoli', true),
('MG', 'Madagascar', NULL, 'africa', 'Indian/Antananarivo', true),
('MW', 'Malawi', NULL, 'africa', 'Africa/Blantyre', true),
('ML', 'Mali', NULL, 'africa', 'Africa/Bamako', true),
('MR', 'Mauritania', NULL, 'africa', 'Africa/Nouakchott', true),
('MU', 'Mauritius', NULL, 'africa', 'Indian/Mauritius', true),
('MA', 'Morocco', NULL, 'africa', 'Africa/Casablanca', true),
('MZ', 'Mozambique', NULL, 'africa', 'Africa/Maputo', true),
('NA', 'Namibia', NULL, 'africa', 'Africa/Windhoek', true),
('NE', 'Niger', NULL, 'africa', 'Africa/Niamey', true),
('NG', 'Nigeria', NULL, 'africa', 'Africa/Lagos', true),
('RW', 'Rwanda', NULL, 'africa', 'Africa/Kigali', true),
('ST', 'Sao Tome and Principe', NULL, 'africa', 'Africa/Sao_Tome', true),
('SN', 'Senegal', NULL, 'africa', 'Africa/Dakar', true),
('SC', 'Seychelles', NULL, 'africa', 'Indian/Mahe', true),
('SL', 'Sierra Leone', NULL, 'africa', 'Africa/Freetown', true),
('SO', 'Somalia', NULL, 'africa', 'Africa/Mogadishu', true),
('ZA', 'South Africa', NULL, 'africa', 'Africa/Johannesburg', true),
('SS', 'South Sudan', NULL, 'africa', 'Africa/Juba', true),
('SD', 'Sudan', NULL, 'africa', 'Africa/Khartoum', true),
('SZ', 'Eswatini', NULL, 'africa', 'Africa/Mbabane', true),
('TZ', 'Tanzania', NULL, 'africa', 'Africa/Dar_es_Salaam', true),
('TG', 'Togo', NULL, 'africa', 'Africa/Lome', true),
('TN', 'Tunisia', NULL, 'africa', 'Africa/Tunis', true),
('UG', 'Uganda', NULL, 'africa', 'Africa/Kampala', true),
('ZM', 'Zambia', NULL, 'africa', 'Africa/Lusaka', true),
('ZW', 'Zimbabwe', NULL, 'africa', 'Africa/Harare', true),
('AU', 'Australia', NULL, 'oceania', 'Australia/Sydney', true),
('FJ', 'Fiji', NULL, 'oceania', 'Pacific/Fiji', true),
('KI', 'Kiribati', NULL, 'oceania', 'Pacific/Tarawa', true),
('MH', 'Marshall Islands', NULL, 'oceania', 'Pacific/Majuro', true),
('FM', 'Micronesia', NULL, 'oceania', 'Pacific/Pohnpei', true),
('NR', 'Nauru', NULL, 'oceania', 'Pacific/Nauru', true),
('NZ', 'New Zealand', NULL, 'oceania', 'Pacific/Auckland', true),
('PW', 'Palau', NULL, 'oceania', 'Pacific/Palau', true),
('PG', 'Papua New Guinea', NULL, 'oceania', 'Pacific/Port_Moresby', true),
('WS', 'Samoa', NULL, 'oceania', 'Pacific/Apia', true),
('SB', 'Solomon Islands', NULL, 'oceania', 'Pacific/Guadalcanal', true),
('TO', 'Tonga', NULL, 'oceania', 'Pacific/Tongatapu', true),
('TV', 'Tuvalu', NULL, 'oceania', 'Pacific/Funafuti', true),
('VU', 'Vanuatu', NULL, 'oceania', 'Pacific/Efate', true),
('AI', 'Anguilla', NULL, 'americas', 'America/Anguilla', true),
('AM', 'Armenia', NULL, 'asia', 'Asia/Yerevan', true),
('AQ', 'Antarctica', NULL, NULL, 'Antarctica/McMurdo', true),
('AS', 'American Samoa', NULL, 'oceania', 'Pacific/Pago_Pago', true),
('AW', 'Aruba', NULL, 'americas', 'America/Aruba', true),
('AX', 'Åland Islands', NULL, 'europe', 'Europe/Mariehamn', true),
('AZ', 'Azerbaijan', NULL, 'asia', 'Asia/Baku', true),
('BL', 'Saint Barthélemy', NULL, 'americas', 'America/St_Barthelemy', true),
('BM', 'Bermuda', NULL, 'americas', 'Atlantic/Bermuda', true),
('BN', 'Brunei', NULL, 'asia', 'Asia/Brunei', true),
('BQ', 'Caribbean Netherlands', NULL, 'americas', 'America/Kralendijk', true),
('CC', 'Cocos Islands', NULL, 'asia', 'Indian/Cocos', true),
('CK', 'Cook Islands', NULL, 'oceania', 'Pacific/Rarotonga', true),
('CW', 'Curaçao', NULL, 'americas', 'America/Curacao', true),
('CX', 'Christmas Island', NULL, 'asia', 'Indian/Christmas', true),
('CY', 'Cyprus', NULL, 'europe', 'Asia/Nicosia', true),
('EH', 'Western Sahara', NULL, 'africa', 'Africa/El_Aaiun', true),
('FK', 'Falkland Islands', NULL, 'americas', 'Atlantic/Stanley', true),
('FO', 'Faroe Islands', NULL, 'europe', 'Atlantic/Faroe', true),
('GE', 'Georgia', NULL, 'asia', 'Asia/Tbilisi', true),
('GF', 'French Guiana', NULL, 'americas', 'America/Cayenne', true),
('GG', 'Guernsey', NULL, 'europe', 'Europe/Guernsey', true),
('GI', 'Gibraltar', NULL, 'europe', 'Europe/Gibraltar', true),
('GL', 'Greenland', NULL, 'americas', 'America/Godthab', true),
('GP', 'Guadeloupe', NULL, 'americas', 'America/Guadeloupe', true),
('GS', 'South Georgia and the South Sandwich Islands', NULL, 'americas', 'Atlantic/South_Georgia', true),
('GU', 'Guam', NULL, 'oceania', 'Pacific/Guam', true),
('IM', 'Isle of Man', NULL, 'europe', 'Europe/Isle_of_Man', true),
('IO', 'British Indian Ocean Territory', NULL, 'asia', 'Indian/Chagos', true),
('JE', 'Jersey', NULL, 'europe', 'Europe/Jersey', true),
('KG', 'Kyrgyzstan', NULL, 'asia', 'Asia/Bishkek', true),
('KH', 'Cambodia', NULL, 'asia', 'Asia/Phnom_Penh', true),
('KP', 'North Korea', NULL, 'asia', 'Asia/Pyongyang', true),
('KY', 'Cayman Islands', NULL, 'americas', 'America/Cayman', true),
('KZ', 'Kazakhstan', NULL, 'asia', 'Asia/Almaty', true),
('LA', 'Laos', NULL, 'asia', 'Asia/Vientiane', true),
('MF', 'Saint Martin', NULL, 'americas', 'America/Marigot', true),
('MM', 'Myanmar', NULL, 'asia', 'Asia/Rangoon', true),
('MN', 'Mongolia', NULL, 'asia', 'Asia/Ulaanbaatar', true),
('MO', 'Macao', NULL, 'asia', 'Asia/Macau', true),
('MP', 'Northern Mariana Islands', NULL, 'oceania', 'Pacific/Saipan', true),
('MQ', 'Martinique', NULL, 'americas', 'America/Martinique', true),
('MS', 'Montserrat', NULL, 'americas', 'America/Montserrat', true),
('NC', 'New Caledonia', NULL, 'oceania', 'Pacific/Noumea', true),
('NF', 'Norfolk Island', NULL, 'oceania', 'Pacific/Norfolk', true),
('NU', 'Niue', NULL, 'oceania', 'Pacific/Niue', true),
('PF', 'French Polynesia', NULL, 'oceania', 'Pacific/Tahiti', true),
('PM', 'Saint Pierre and Miquelon', NULL, 'americas', 'America/Miquelon', true),
('PN', 'Pitcairn', NULL, 'oceania', 'Pacific/Pitcairn', true),
('PR', 'Puerto Rico', NULL, 'americas', 'America/Puerto_Rico', true),
('PS', 'Palestine', NULL, 'asia', 'Asia/Gaza', true),
('RE', 'Réunion', NULL, 'africa', 'Indian/Reunion', true),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', NULL, 'africa', 'Atlantic/St_Helena', true),
('SJ', 'Svalbard and Jan Mayen', NULL, 'europe', 'Arctic/Longyearbyen', true),
('SX', 'Sint Maarten', NULL, 'americas', 'America/Lower_Princes', true),
('TC', 'Turks and Caicos Islands', NULL, 'americas', 'America/Grand_Turk', true),
('TF', 'French Southern Territories', NULL, 'africa', 'Indian/Kerguelen', true),
('TJ', 'Tajikistan', NULL, 'asia', 'Asia/Dushanbe', true),
('TK', 'Tokelau', NULL, 'oceania', 'Pacific/Fakaofo', true),
('TL', 'Timor-Leste', NULL, 'asia', 'Asia/Dili', true),
('TM', 'Turkmenistan', NULL, 'asia', 'Asia/Ashgabat', true),
('UM', 'United States Minor Outlying Islands', NULL, 'americas', 'Pacific/Wake', true),
('UZ', 'Uzbekistan', NULL, 'asia', 'Asia/Tashkent', true),
('VG', 'Virgin Islands (UK)', NULL, 'americas', 'America/Tortola', true),
('VI', 'Virgin Islands (US)', NULL, 'americas', 'America/St_Thomas', true),
('WF', 'Wallis and Futuna', NULL, 'oceania', 'Pacific/Wallis', true),
('YT', 'Mayotte', NULL, 'africa', 'Indian/Mayotte', true);