-- Add missing timezones that are causing foreign key constraint violations
-- This migration adds only the timezones that are missing from the previous migration

INSERT INTO timezones (name, display_name, is_active) VALUES
('America/Antigua', 'America/Antigua (GMT)', true),
('America/Dominica', 'America/Dominica (GMT)', true),
('America/Grenada', 'America/Grenada (GMT)', true),
('America/St_Kitts', 'America/St_Kitts (GMT)', true),
('America/St_Lucia', 'America/St_Lucia (GMT)', true),
('America/St_Vincent', 'America/St_Vincent (GMT)', true),
('Europe/Vaduz', 'Europe/Vaduz (GMT)', true),
('Europe/Vatican', 'Europe/Vatican (GMT)', true),
('Europe/San_Marino', 'Europe/San_Marino (GMT)', true),
('Europe/Sarajevo', 'Europe/Sarajevo (GMT)', true),
('Europe/Skopje', 'Europe/Skopje (GMT)', true),
('Europe/Ljubljana', 'Europe/Ljubljana (GMT)', true),
('Europe/Podgorica', 'Europe/Podgorica (GMT)', true),
('Europe/Bratislava', 'Europe/Bratislava (GMT)', true),
('Europe/Zagreb', 'Europe/Zagreb (GMT)', true),
('Asia/Aden', 'Asia/Aden (GMT)', true),
('Asia/Bahrain', 'Asia/Bahrain (GMT)', true),
('Asia/Kuwait', 'Asia/Kuwait (GMT)', true),
('Asia/Muscat', 'Asia/Muscat (GMT)', true),
('Africa/Addis_Ababa', 'Africa/Addis_Ababa (GMT)', true),
('Africa/Asmara', 'Africa/Asmara (GMT)', true),
('Africa/Bamako', 'Africa/Bamako (GMT)', true),
('Africa/Bangui', 'Africa/Bangui (GMT)', true),
('Africa/Banjul', 'Africa/Banjul (GMT)', true),
('Africa/Blantyre', 'Africa/Blantyre (GMT)', true),
('Africa/Brazzaville', 'Africa/Brazzaville (GMT)', true),
('Africa/Bujumbura', 'Africa/Bujumbura (GMT)', true),
('Africa/Conakry', 'Africa/Conakry (GMT)', true),
('Africa/Dakar', 'Africa/Dakar (GMT)', true),
('Africa/Douala', 'Africa/Douala (GMT)', true),
('Africa/Freetown', 'Africa/Freetown (GMT)', true),
('Africa/Gaborone', 'Africa/Gaborone (GMT)', true),
('Africa/Harare', 'Africa/Harare (GMT)', true),
('Africa/Juba', 'Africa/Juba (GMT)', true),
('Africa/Kampala', 'Africa/Kampala (GMT)', true),
('Africa/Kigali', 'Africa/Kigali (GMT)', true),
('Africa/Kinshasa', 'Africa/Kinshasa (GMT)', true),
('Africa/Libreville', 'Africa/Libreville (GMT)', true),
('Africa/Lome', 'Africa/Lome (GMT)', true),
('Africa/Luanda', 'Africa/Luanda (GMT)', true),
('Africa/Maseru', 'Africa/Maseru (GMT)', true),
('Africa/Mbabane', 'Africa/Mbabane (GMT)', true),
('Africa/Mogadishu', 'Africa/Mogadishu (GMT)', true),
('Africa/Niamey', 'Africa/Niamey (GMT)', true),
('Africa/Nouakchott', 'Africa/Nouakchott (GMT)', true),
('Africa/Ouagadougou', 'Africa/Ouagadougou (GMT)', true),
('Africa/Porto-Novo', 'Africa/Porto-Novo (GMT)', true),
('Africa/Sao_Tome', 'Africa/Sao_Tome (GMT)', true),
('Indian/Antananarivo', 'Indian/Antananarivo (GMT)', true),
('Indian/Comoro', 'Indian/Comoro (GMT)', true)
ON CONFLICT (name) DO NOTHING;